export const greating = [
  {id: 1, text: 'Inspiring images for everyone.'},
  {id: 2, text: 'Discover stunning photography.'},
  {id: 3, text: 'Find the perfect photo for your project.'},
  {id: 4, text: 'Unleash your creativity with Unsplash.'},
  {id: 5, text: 'Millions of free, high-quality photos at your fingertips.'},
  {id: 6, text: 'Explore endless possibilities with Unsplash.'},
  {id: 7, text: "Join the world's most generous community of photographers."},
  {id: 8, text: 'Experience the beauty of Unsplash.'},
  {id: 9, text: 'Elevate your designs with Unsplash.'},
  {id: 10, text: "Uncover the world's best photography with Unsplash."},
];
export const categories = [
  {id: 'wallpapers', text: 'Wallpapers'},
  {id: 'nature', text: 'Nature'},
  {id: 'people', text: 'People'},
  {id: 'architecture', text: 'Architecture'},
  {id: 'current-events', text: 'Current Events'},
  {id: 'fashion', text: 'Fashion'},
  {id: 'food-drink', text: 'Food & Drink'},
  {id: 'interiors', text: 'Interiors'},
  {id: 'street-photography', text: 'Street Photography'},
  {id: 'technology', text: 'Technology'},
  {id: 'travel', text: 'Travel'},
  {id: 'textures-patterns', text: 'Textures & Patterns'},
  {id: 'animals', text: 'Animals'},
  {id: 'business-work', text: 'Business & Work'},
  {id: 'health-wellness', text: 'Health & Wellness'},
  {id: 'holidays', text: 'Holidays'},
  {id: 'industrial', text: 'Industrial'},
  {id: 'music', text: 'Music'},
  {id: 'objects', text: 'Objects'},
  {id: 'art', text: 'Art'},
  {id: 'culture', text: 'Culture'},
];

